import type { Plugin } from "./types";

export const PLUGIN_CATALOG: Plugin[] = [
  {
    id: "web_search",
    name: "Web Search",
    summary: "Search the live web and summarize results.",
    category: "Research",
    tools: ["web_search"],
  },
  {
    id: "fetch_url",
    name: "Fetch URL",
    summary: "Fetch the contents of a page.",
    category: "Research",
    tools: ["fetch_url"],
  },
  {
    id: "files",
    name: "Workspace files",
    summary: "Read and write files in /workspace.",
    category: "Computer",
    tools: ["files_list", "files_read", "files_write"],
  },
  {
    id: "image_gen",
    name: "Image gen",
    summary: "Generate images from a prompt (Gemini via gateway or BYOK).",
    category: "Create",
    tools: ["image_gen"],
  },
  {
    id: "browser",
    name: "Browser",
    summary: "Open sites, click, and type on the shared computer.",
    category: "Computer",
    tools: ["browser_navigate", "browser_act"],
  },
  {
    id: "terminal_sandbox",
    name: "Sandbox terminal",
    summary: "Run commands in a sandboxed terminal, not on the host.",
    category: "Computer",
    tools: ["terminal_run"],
  },
  {
    id: "memory",
    name: "Memory",
    summary: "Store stable notes per Bot.",
    category: "Core",
    tools: ["memory_write"],
  },
  {
    id: "message_bot",
    name: "Message bot",
    summary: "Hand work to another Bot.",
    category: "Team",
    tools: ["message_bot"],
  },
  {
    id: "create_routine",
    name: "Routines",
    summary: "Schedule repeating work.",
    category: "Team",
    tools: ["create_routine"],
  },
  {
    id: "gmail",
    name: "Gmail",
    summary: "Connect via MCP URL or app password. Drafts only — never send in secret.",
    category: "Connectors",
    tools: ["gmail_draft"],
    mcpUrl: "",
  },
  {
    id: "slack",
    name: "Slack",
    summary: "MCP or bot token. Posts wait for approval.",
    category: "Connectors",
    tools: ["slack_post"],
  },
  {
    id: "github",
    name: "GitHub",
    summary: "PAT or MCP. Browse issues and PRs; writes wait for approval.",
    category: "Connectors",
    tools: ["github_list"],
  },
];

export const BOT_TEMPLATES = [
  {
    id: "chief",
    name: "Chief of Staff",
    title: "Coordination",
    description: "Keeps the other Bots focused and only pulls you in for decisions.",
    color: "#2EE6A6",
    shape: "stadium" as const,
    systemPrompt:
      "Je bent Chief of Staff. Routeer werk, vat samen, en stoor de gebruiker alleen voor oordelen. Gebruik message_bot voor specialisten.",
  },
  {
    id: "inbox",
    name: "Inbox",
    title: "Triage",
    description: "Reads mail and chat, drafts replies, and sends nothing without approval.",
    color: "#3B82F6",
    shape: "squircle" as const,
    systemPrompt: "Je bent Inbox-triage. Concepten eerst. Versturen vereist approval.",
  },
  {
    id: "research",
    name: "Research",
    title: "Research",
    description: "Searches, reads sources, and returns a citation list.",
    color: "#F59E0B",
    shape: "capsule" as const,
    systemPrompt: "Je bent Research. Citeer bronnen. Geen verzinsels als je kunt zoeken.",
  },
  {
    id: "builder",
    name: "Builder",
    title: "Code & deploys",
    description: "Writes code and tests, and leaves diffs in /workspace.",
    color: "#A78BFA",
    shape: "hex" as const,
    systemPrompt: "Je bent Builder. Kleine diffs, tests erbij, geen secrets in code.",
  },
];
