import type { Plugin } from "./types";

export const PLUGIN_CATALOG: Plugin[] = [
  {
    id: "web_search",
    name: "Web Search",
    summary: "Zoek live op het web en vat resultaten samen.",
    category: "Research",
    tools: ["web_search"],
  },
  {
    id: "fetch_url",
    name: "Fetch URL",
    summary: "Haal de inhoud van een pagina op.",
    category: "Research",
    tools: ["fetch_url"],
  },
  {
    id: "files",
    name: "Workspace files",
    summary: "Lees en schrijf bestanden in /workspace.",
    category: "Computer",
    tools: ["files_list", "files_read", "files_write"],
  },
  {
    id: "image_gen",
    name: "Image gen",
    summary: "Maak afbeeldingen vanuit een prompt (Gemini via gateway of BYOK).",
    category: "Create",
    tools: ["image_gen"],
  },
  {
    id: "browser",
    name: "Browser",
    summary: "Open sites, klik en typ op de gedeelde computer.",
    category: "Computer",
    tools: ["browser_navigate", "browser_act"],
  },
  {
    id: "terminal_sandbox",
    name: "Sandbox terminal",
    summary: "Voer commando's uit in een afgeschermde sandbox, niet op de host.",
    category: "Computer",
    tools: ["terminal_run"],
  },
  {
    id: "memory",
    name: "Memory",
    summary: "Sla stabiele notities per bot op.",
    category: "Core",
    tools: ["memory_write"],
  },
  {
    id: "message_bot",
    name: "Message bot",
    summary: "Stuur werk door naar een andere bot.",
    category: "Team",
    tools: ["message_bot"],
  },
  {
    id: "create_routine",
    name: "Routines",
    summary: "Plan herhalend werk op een schema.",
    category: "Team",
    tools: ["create_routine"],
  },
  {
    id: "gmail",
    name: "Gmail",
    summary: "Koppel via MCP-URL of app-wachtwoord. Concepten, nooit stiekem versturen.",
    category: "Connectors",
    tools: ["gmail_draft"],
    mcpUrl: "",
  },
  {
    id: "slack",
    name: "Slack",
    summary: "MCP of bot-token. Posts achter approval.",
    category: "Connectors",
    tools: ["slack_post"],
  },
  {
    id: "github",
    name: "GitHub",
    summary: "PAT of MCP. Issues en PRs bekijken, writes achter approval.",
    category: "Connectors",
    tools: ["github_list"],
  },
];

export const BOT_TEMPLATES = [
  {
    id: "chief",
    name: "Chief of Staff",
    title: "Coördinatie",
    description: "Houdt de andere bots gericht en haalt jou er alleen bij voor beslissingen.",
    color: "#2EE6A6",
    shape: "stadium" as const,
    systemPrompt:
      "Je bent Chief of Staff. Routeer werk, vat samen, en stoor de gebruiker alleen voor oordelen. Gebruik message_bot voor specialisten.",
  },
  {
    id: "inbox",
    name: "Inbox",
    title: "Triage",
    description: "Leest mail en chat, maakt concepten, stuurt niets zonder goedkeuring.",
    color: "#3B82F6",
    shape: "squircle" as const,
    systemPrompt: "Je bent Inbox-triage. Concepten eerst. Versturen vereist approval.",
  },
  {
    id: "research",
    name: "Research",
    title: "Onderzoek",
    description: "Zoekt, leest bronnen, en levert een bronnenlijst.",
    color: "#F59E0B",
    shape: "capsule" as const,
    systemPrompt: "Je bent Research. Citeer bronnen. Geen verzinsels als je kunt zoeken.",
  },
  {
    id: "builder",
    name: "Builder",
    title: "Code & deploys",
    description: "Schrijft code, tests, en laat diffs achter in /workspace.",
    color: "#A78BFA",
    shape: "hex" as const,
    systemPrompt: "Je bent Builder. Kleine diffs, tests erbij, geen secrets in code.",
  },
];
